[package]
name = "barony-mod-manager"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = "0.3"
reqwest = "0.11.4"
serde = { version = "1.0.130", features = ["derive"] }
serde_with = { version = "1.10", features = ["chrono"]}
serde_json = "1.0"
chrono = "0.4"
