name: Create release

on: [push]
    # tags:
    #   - 'v[0-9]+.*'

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Build
        run: |
          sudo apt install libfreetype6-dev gperf
          cd barony-mod-manager
          cargo build --release
          strip target/release/barony-mod-manager
          mv target/release/barony-mod-manager target/release/barony-mod-manager_amd64

      # - name: Release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     files: |
      #       barony-mod-manager/target/release/barony-mod-manager_amd64
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Build
        run: |
          cd barony-mod-manager
          cargo build --release

      # - name: Release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     files: target/release/barony-mod-manager.exe
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-mac:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-apple-darwin
          default: true
          override: true

      - name: Build for mac
        run: |
          cd barony-mod-manager
          cargo build --release
          strip target/release/barony-mod-manager
          mv target/release/barony-mod-manager target/release/barony-mod-manager_darwin

      # - name: Release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     files: |
      #       target/release/PROJECT_NAME_darwin
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
